# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Variables
  vm_name = "node1"
  vm_box = "generic/ubuntu2004"
  box_version = "4.3.12"
  vm_ip = ENV['VM_IP'] || "192.168.60.60" # This defines the VM ip using the ENV varible to match it to Ansible's config
  vm_memory = "1024"
  vm_cpu = 1

  # Config
  config.vm.box = vm_box
  config.vm.box_version = box_version
  config.vm.hostname = vm_name
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: vm_ip

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.customize ["modifyvm", :id, "--name", vm_name]

    vb.cpus = vm_cpu
    vb.memory = vm_memory
  end

  config.vm.provision "shell", path: "vagrant_example/provision.sh"

end
