---
- name: Preliminary control-node checks
  hosts: localhost
  vars:
    ansible_vault_path: "./secrets.yml"
  gather_facts: false
  tasks:

    - name: Check if vault file exists
      ansible.builtin.stat:
        path: "{{ ansible_vault_path }}"
      register: vault_status

    - name: Fail if the vault file does not exist
      ansible.builtin.debug:
        msg: "Vault file does not exist"
      when: vault_status.stat.exists == false # catches the 'false' status of vault_status
      failed_when: vault_status.stat.exists == false  # throws an error if it is 'false'

    - name: Check if vault is decryptable
      ansible.builtin.include_vars:
        file: "{{ ansible_vault_path }}"
      register: vault_vars

    - name: Fail if unable to decrypt the vault
      ansible.builtin.debug:
        msg: "Unable to decrypt the vault file. Check the password or the file"
      when: vault_vars is not defined

    - name: Fail if the mandatory secrets are not defined
      fail:
        msg: "The variable '{{ item }}' is not defined"
      loop:
        - inception_user_password
      when: lookup('vars', item) is not defined

- name: Install docker
  hosts: inception_nodes
  tasks:

    - name: Remove dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        update-cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Set Docker architecture
      set_fact:
        docker_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

    - name: Add dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update-cache: yes
      loop:
        - ca-certificates
        - curl
        - gnupg

    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch={{ docker_arch }}]  https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update-cache: yes

    - name: Add dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update-cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Create docker group
      group:
        name: docker
        state: present

- name: Set-up inception
  hosts: inception_nodes
  vars_files:
    - "./secrets.yml"
  tasks:

    - name: Create inception user
      ansible.builtin.user: 
        name: "{{ deploy_user }}"
        comment: This user runs the inception stack
        append: yes
        create_home:
        groups: docker
        password: "{{ inception_user_password }}" # The password is defined in the secret.yml vault

    - name: Copy inception sources
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/Inception"
        dest: "/home/{{ deploy_user }}/"
        mode: '0755'
        directory_mode: '0755'
        owner: "{{ deploy_user }}"
        group: docker
