---
- name: Test first play
  hosts: inception_nodes
  tasks:
    - name: Create test group
      ansible.builtin.group:
        name: test_group
    - name: Create test user and add to test group
      ansible.builtin.user: 
        name: test_user
        comment: This is the test user
        group: test_group

- name: Install docker
  hosts: inception_nodes
  tasks:
    - name: Add dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update-cache: yes
      loop:
        - ca-certificates
        - curl
        - gnupg
    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name:
      apt_repository:
        repo: deb [arch=$(dpkg --print-architecture)]  https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
    - name: Add dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update-cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

- name: First play - create group1 and user1
  hosts: localhost
  become: true
  tasks:
    - name: Create group1
      ansible.builtin.group:
        name: group1
        state: present

    - name: Create user1 and add to group1
      ansible.builtin.user:
        name: user1
        group: group1
        state: present

- name: Second play - create group2 and user2
  hosts: localhost
  become: true
  tasks:
    - name: Create group2
      ansible.builtin.group:
        name: group2
        state: present

    - name: Create user2 and add to group2
      ansible.builtin.user:
        name: user2
        group: group2
        state: present
