all:
  children:
    inception_nodes:
      hosts:
        vagrant_vm:
          ansible_host: "{{ lookup('env', 'ANSIBLE_TARGET_IP') }}" # This lookup uses the control node env, to read the target node's env, you would use 'ansible.builtin.env'.
          ansible_user: deploy
      vars:
        example_group_var_inventory:  "foobar" # These variables can also be stored in the group_vars/ or host_vars/ directories. The yaml files need to be named like the corresponding group (inception_nodes.yml) or host (vagrant_vm.yml)
